spring:
  application:
    name: realtime-stock

  rabbitmq:
    host: 3.38.242.178
    port: 5672
    username: test
    password: test
    exchange:
      name: (AMQP default)
    recvQueue:
      name: main_to_stock
    sendQueue:
      name: stock_to_alarm
server:
  port: 8083