spring:
  application:
    name: stock-system
  jwt:
    secret: ${JWT_SECRET}

  ag:
    url: ${AG_URL}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false


  rabbitmq:
    host: ${MQ_HOST}
    port: ${MQ_PORT}
    username: ${MQ_USERNAME}
    password: ${MQ_PASSWORD}
    exchange:
      name: (AMQP default)
    sendQueue:
      name: stock_to_alarm
    mainToStock:
      name: offer_to_trade

  jwt:
    secret: ${JWT_SECRET}

server:
  port: 8082