spring:
  application:
    name: ag-gateway
  jwt:
    secret: ${JWT_SECRET}

server:
  port: 8080

logging:
  level:
    root: info

route:
  url:
    group-investment: ${GROUP_INVESTMENT_URL}
    stock-system: ${STOCK_SYSTEM_URL}
    invest-reference: ${INVEST_REFERENCES_URL}
    chatting: ${CHAT_URL}
    alarm: ${ALARM_URL}