spring:
  application:
    name: ag-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: group-investment
            uri:
              http://localhost:8081
            predicates:
              - Path=/group-investment/**
            filters:
              - StripPrefix=1

          - id: stock-system
            uri:
              http://localhost:8082
            predicates:
              - Path=/invest-system/**
            filters:
              - StripPrefix=1

          - id: invest-references-service
            uri:
              http://localhost:8083
            predicates:
              - Path=/invest-references/**
            filters:
              - StripPrefix=1

          - id: chatting
            uri:
              http://localhost:8084
            predicates:
              - Path=/chatting/**
            filters:
              - StripPrefix=1

          - id: alarm
            uri:
              http://localhost:8085
            predicates:
              - Path=/alarm/**
            filters:
              - StripPrefix=1
server:
  port: 8080
