spring:
  application:
    name: alarm
  jwt:
    secret: ${JWT_SECRET}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${ALARM_URL}
    username: ${ALARM_USERNAME}
    password: ${ALARM_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  jwt:
    secret: ${JWT_SECRET}

  ag:
    url: ${AG_URL}

  rabbitmq:
    host: ${MQ_HOST}
    port: ${MQ_PORT}
    username: ${MQ_USERNAME}
    password: ${MQ_PASSWORD}
    exchange:
      name: (AMQP default)
    reg-token-queue:
      name: main_to_alarm
    chatToAlarmQueue:
      name: chat_to_alarm
    stockTradeQueue:
      name: stock_to_alarm

fcm:
  service:
    key: ./serviceAccountKey.json

server:
  port: 8085
