spring:
  application:
    name:
      alarm

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PASSWD}


  rabbitmq:
    host: 3.38.242.178
    port: 5672
    username: test
    password: test
    exchange:
      name: (AMQP default)
    recvMainQueue:
      name: main_to_alarm
    recvChatQueue:
      name: chat_to_alarm
    recvStockQueue:
      name: stock_to_alarm

fcm:
  service:
    key:
      ./serviceAccountKey.json