spring:
  application:
    name: chatting

  rabbitmq:
    host: 3.38.242.178
    port: 5672
    username: test
    password: test
    exchange:
      name: (AMQP default)
    recvChatQueue:
      name: chat_to_alarm

  data:
    redis:
      host: localhost
      port: 6379


redis:
  chatroom:
    prefix: "chat:"

chat:
  path: http://localhost:8082

server:
  port: 8082
