spring:
  application:
    name: chatting


  data:
    redis:
      host: localhost
      port: 6379


redis:
  chatroom:
    prefix: "chat:"

chat:
  path: http://localhost:8082

server:
  port: 8082