spring:
  application:
    name:
      alarm
  port: 8082

  rabbitmq:
    host: 3.38.242.178
    port: 5672
    username: test
    password: test
    exchange:
      name: (AMQP default)
    recvChatQueue:
      name: chat_to_alarm