spring:
  application:
    name: chatting
  jwt:
    secret: ${JWT_SECRET}

  rabbitmq:
    host: ${MQ_HOST}
    port: ${MQ_PORT}
    username: ${MQ_USERNAME}
    password: ${MQ_PASSWORD}
    exchange:
      name: (AMQP default)
    queue:
      name: chat_to_alarm

  data:
    redis:
      host: localhost
      port: 6379
    cache:
      type: redis

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

redis:
  chatroom:
    prefix: "chat:"
  cache:
    ttl: 1200
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

chat:
  path: http://localhost:8082

server:
  port: 8082
