name: CI/CD for Group-investment-Module Gradle Spring Boot Application

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NAME: 'alarm'
      EC2_HOST: ${{ secrets.ALARM_EC2_HOST }}
      EC2_PORT: ${{ secrets.ALARM_EC2_PORT }}
      EC2_KEY: ${{ secrets.EC2_KEY }}
      AWS_ROLE: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      PORT: ${{ secrets.SCP_PORT }}
      EC2_PEM_KEY: ${{ secrets.EC2_PEM_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle for ${{ env.NAME }}
        run: ./gradlew :${{ env.NAME }}:bootJar

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'ap-northeast-2'
          role-to-assume: ${{ env.AWS_ROLE }} # IAM Role ARN

      - name: 서비스 실행
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.EC2_HOST }}
          username: ubuntu
          key: ${{ env.EC2_PEM_KEY }}
          port: 22
          script: |
            sudo rm -rf /home/ubuntu/${{ env.NAME }}/*.jar
            lsof -t -i tcp:8080 | xargs kill -9
            git checkout main
            git pull origin main
            /home/ubuntu/${{ env.NAME }}/gradlew :${{ env.NAME }}:bootJar
            nohup env $(cat /home/ubuntu/${{ env.NAME }}.env | xargs) java -jar /home/ubuntu/${{ env.NAME }}-1.0.0.jar &
