
name: CI/CD for Multi-Module Gradle Spring Boot Application on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Git pull, build and deploy on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.CHAT_EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PEM_KEY }}
          port: 22
          script: |
            cd pda-armagyetdon-backend/
            git pull origin feat/134-server-cicd
            cd chatting
            sudo chmod +x ./gradlew 
            ./gradlew :chatting:bootJar --no-daemon
            sudo systemctl stop chatting
            sleep 3
            sudo systemctl start chatting
            sleep 10
            sudo systemctl status chatting
