
name: CI/CD for Multi-Module Gradle Spring Boot Application on EC2

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Git pull, build and deploy on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.GATEWAY_EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PEM_KEY }}
          port: 22
          script: |
            cd pda-armagyetdon-backend/
            git pull origin feat/134-server-cicd
            cd ag-gateway
            sudo chmod +x ./gradlew 
            ./gradlew :ag-gateway:bootJar --no-daemon
            sudo systemctl stop ag-gateway
            sleep 3
            sudo systemctl start ag-gateway
            sleep 10
            sudo systemctl status ag-gateway
