name: CI/CD for group-investment Spring Boot Application on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Git pull, build and deploy on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.GROUP_INVESTMENT_EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PEM_KEY }}
          port: 22
          script: |
            cd pda-armagyetdon-backend/
            git pull origin main
            cd group-investment
            sudo chmod +x ./gradlew 
            ./gradlew :group-investment:bootJar --no-daemon
            sudo systemctl stop group-investment
            sleep 3
            sudo systemctl start group-investment
            sleep 10
            sudo systemctl status group-investment
