name: CI/CD for invest-references Gradle Spring Boot Application on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Git pull, build and deploy on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.INVEST_REFERENCES_EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PEM_KEY }}
          port: 22
          script: |
            cd pda-armagyetdon-backend/
            cd invest-references
            git pull origin main
            sudo chmod +x ./gradlew 
            ./gradlew :invest-references:bootJar --no-daemon
            sudo systemctl stop invest-references
            sleep 3
            sudo systemctl start invest-references
            sleep 10
            sudo systemctl status invest-references
