name: CI/CD for Stock Gradle Spring Boot Application on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Git pull, build and deploy on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.STOCK_SYSTEM_EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PEM_KEY }}
          port: 22
          script: |
            cd pda-armagyetdon-backend/
            git pull origin main
            cd stock-system
            sudo chmod +x ./gradlew 
            ./gradlew :stock-system:bootJar --no-daemon
            sudo systemctl stop stock-system
            sleep 3
            sudo systemctl start stock-system
            sleep 10
            sudo systemctl status stock-system
